
pickle_sandbox_blog:
    resource: @SandboxBlogBundle/Resources/config/routing.yml


#PickleBlogAdminBundle:
#    resource: "@PickleBlogAdminBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#PickleAdminBundle:
#    resource: "@PickleAdminBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#
#PickleBlogBundle:
#    resource: "Pickle\Bundle\BlogBundle\Controller\BlogController"
#    type:     annotation
#    prefix:   /
#
#homepage:
#    pattern:  /
#    defaults: { _controller: PickleBlogBundle:Blog:index }
#
#blog_list:
#    pattern:  /
#    defaults: { _controller: PickleBlogBundle:Blog:index }
